### ISSUE TITLE
Substitution and lambdas prove false

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#113]
See https://github.com/SkySkimmer/andromeda/blob/binder-vars/tests/lambda-where-broken.m31

**Comment by andrejbauer** [comment]
Good catch. We need to do some context joining whenever we perform an abstraction (in `Eval` these would be in `infer_lambda`, `check_lambda` and likewise for products). For instance, in `infer_lambda`  we see:

    and infer_lambda env ~loc xus c =
      let rec fold env ctx zs xws  = function
          | [] ->
             infer env c >>= as_term ~loc:(snd c) >>= fun (ctxe, e, t') ->
             let e = Tt.abstract zs e in
             let t' = Tt.abstract_ty zs t' in
             let ctx = Context.join ctx ctxe in
             let ctx = Context.abstract ~loc ctx zs in
             let xws = List.rev xws in
             let lam = Tt.mk_lambda ~loc xws e t' in
             let prod = Tt.mk_prod_ty ~loc xws t' in
             Value.return (ctx, lam, prod)
          | (x, None) :: _ ->
             Error.runtime ~loc "cannot infer the type of %t" (Name.print_ident x)
          | (x, Some c) :: xus ->
             check_ty env c >>= fun ((ctxu, u') as u) ->
             (* XXX equip x with location and use for [~loc]. *)
             let z, env = Environment.add_fresh ~loc:Location.unknown env x u in
             let w' = Tt.abstract_ty zs u' in
             let ctx = Context.join ctx ctxu in
             fold env ctx (z :: zs) ((x, w') :: xws) xus
      in
      fold env Context.empty [] [] xus

The problem is in the recursive step of `fold`. *After* the recursive call to `fold` we need to join the output context with `z : u` as there is no guarantee that `z` actually received type `u`. I hope that would fix the problem.

**Comment by andrejbauer** [comment]
Actually, we could also join the context `ctx` with `xws` in the base case, to take care of all of them at once.

**Comment by SkySkimmer** [comment]
This isn't a join issue. What happens is we derive
`x : Type, y : empty |- y : empty`
then we abstract to get `x : Type |- lambda [y : x] y : forall [y : x] empty`
So when we abstract `z` in `ctx |- ...` we actually need to abstract `z : T` and check that this is also the type of `z` in `ctx`.

**Comment by andrejbauer** [comment]
Isnt' this what the join will accomplish?

**Comment by SkySkimmer** [comment]
It would do something like

    Let ignore := fun a b => match a with
      | |- _ : ?ta =>
        (lambda [_ : ta] b) a
      end.


    Let f := λ [x : Type] [y : x] assume eq : x == empty in ignore eq (y where x := empty).
which fails when abstracting `x`. (the `ignore` is just a trick to get `eq` in the context).

**Comment by andrejbauer** [comment]
Right, if we perform a context join then it might introduce `eq` which will cause abstraction to fail. I am actually inclined to change context join so that it just fails instead of introducing an `eq`. Or maybe it should trigger an equailty check, I do not know. I suspect that the mysteriously appearing `eq`'s won't be helpful in practice.

**Comment by haselwarter** [comment]
> I suspect that the mysteriously appearing eq's won't be helpful in practice.

Except that in some cases the user might be able to discharge them via a
handler. But here there won't be a chance to run such a handler because
we just fail trying to abstract it. I'm reluctant to making that an
operation too.

A solution that seems sane is to run an equality check just before
abstracting over the variables from the binder. Mostly it'll be alpha.

**Comment by andrejbauer** [comment]
I think the universe wants everything to be in the monad.
