### ISSUE TITLE
What invariants do we maintain?

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#158]
We need to stop and think about what invariants we are maintaining. @haselwarter should be interested in this as he's likely to end up having to prove soundness of Andromeda :-) Let me try to give an outline, and perhaps @haselwarter can fix it and flesh it out.

1. We assign to every term in a context its *natural type*, as @vladimirias did it in early notes on HTS. This is the obvious type that one can read off a term immediately. For instance: the natural type of a variable is read from the context, the natural type of `λ x : A . B . e` is `∏(x : A) B`, etc.
2. Prove that if a term `e` has a type in context `Γ` then it also has its natural type in the same context.
3. We probably also need uniqueness of typing: if a term in a context has types `A` and `B` then `A ≡ B` in the same context.
4. We maintain the following invariants in the nucleus.
    1. If the value `Γ ⊢ e : A` is computed then `Γ ⊢ e : A` is derivable from the constants in the runtime environment.
    2. If the value `Γ ⊢ e : A` is computed then `Γ/A ⊢ A type` is derivable from the constants in the runtime environment. Here `Γ/A` is the subcontext of `Γ` which contains only the assumptions mentioned by `A`.
    3. If the value `Γ ⊢ e : A` is computed then `Γ/e ⊢ e : B` is derivable from the constants in the runtime environment. Here `Γ/e` is as before and `B` is the natural type of `e`.

Furthermore, we should somehow formulate the fact that we try to keep `Γ` minimal, i.e., it contains only the "necessary" assumptions. Likewise, tems and types should only mention those assumptions that are actually needed. For instance, we should never generate `Type` with assumptions attached to it.

There are rules which require us to record assumptions, but these assumptions can be attached neither to the term nor the type. Consider conversion:

     Γ ⊢ e : A    Δ ⊢ A ≡ B
    ------------------------
         Γ ⋈ Δ ⊢ e : B 

Here it would be wrong to attach the assumptions `Δ` to `B` or to `e` because both `e` and `B` need no assumptions to satisy the invariants ii and iii above. The *judgement itself* needs the assumptions, not its constituent parts. At the moment the code wrongly attaches `Δ` to `B` and we need to fix this.

A consequence of this is that we can never strengthen anything (remove things from the context), but this is ok because we always keep the context minimal. And to answer @SkySkimmer's question from #153, pattern matching should always create minimal contexts possible, and the user will never get the option of `restrict`ing, or srenthening the context. Strengthening is not valid.

**Comment by SkySkimmer** [comment]
>Furthermore, we should somehow formulate the fact that we try to keep Γ minimal, i.e., it contains only the "necessary" assumptions. Likewise, tems and types should only mention those assumptions that are actually needed. For instance, we should never generate Type with assumptions attached to it.
This is incorrect. First, the current code doesn't actually keep the context minimal (specifically in matching, but since it wasn't considered a requirement there may be other places).
Secondly it is possible to get a `Type` term with assumptions on it, because the invariant iii isn't quite as stated.

Invariant iii: for every derived judgement the assumptions on a subterm are sufficient to derive the associated judgement.

Essentially assumptions are used to restore the free variable information needed for strengthening which was lost due to equality reflection. That's why just like free variables in other theories they're part of the term.

For every judgement `Γ ⊢ e : t` and subterm `f` of `e`, there is a derived judgement `Δ ⊢ f : u` where `Δ` is obtained from `Γ` by adding the variables bound above `f` in `e` and `u` is obtained the use of `f` in its immediate superterm of `f` in `e` (if `f` is `e` then `u` is `t`). In other words it's the judgement that `f` must verify in order for its use to be OK.
The assumptions on `f` together with the ones in the types of the variables of `Δ` tell us which variables of `Δ` are actually needed to derive the judgement, and which ones can be strengthened away. This is necessary as even if `Γ` is minimal `Δ` generally isn't.
For instance in a term (application annotations omitted)

    λ x y : A, prod A A, pair A A x y
The derived judgement for `y` is `x : A, y : A ⊢ y : A`, and only after producing it can we strengthen away `x` to get a minimal judgement.

As to natural types, we have the following statement of typing uniqueness as part of the underlying theory, replacing points 2 and 3:
if `Γ ⊢ e : A` is derivable and `B` is the natural type of `e` in `Γ`, then `Γ ⊢ A == B` (and by the conversion rule `Γ ⊢ e : B`).
This is because the only way to derive a judgement for `e` is to use the appropriate formation rule for `e`'s top constructor, which produces the natural type, then a bunch of conversion rules which preserve equality of the type with the natural type.

>A consequence of this is that we can never strengthen anything (remove things from the context), but this is ok because we always keep the context minimal. And to answer @SkySkimmer's question from #153, pattern matching should always create minimal contexts possible.
That's strengthening though. The sub-judgements we get from looking at a term's structure don't have minimal context, we strengthen it afterwards. It is however possible to do so implicitly without user action.

**Comment by andrejbauer** [comment]
We'll discuss this live, there's only so much writing I can do in utf-8.

**Comment by andrejbauer** [comment]
>Invariant iii: for every derived judgement the assumptions on a subterm are sufficient to derive the >associated judgement.

Can you write this in symbols? What is the "associated judgement"?

**Comment by SkySkimmer** [comment]
For the judgement `ctx |- lambda x : A. B. e : T` the associated judgements for the immediate subterms are
`ctx |- A type`
`ctx, x : A |- B type` (notice how we added `x` to the context even though it might be possible to derive the judgement without it)
`ctx, x : A |- e : B` (technically this one implies the previous 2, but when matching we get the first one and this one)
Then for deeper subterms you just do it recursively, and other type constructors should be easy to figure out.

In other words it's the inversion of the typing rules.

We could also consider the type `T` a subterm with associated judgement `ctx |- T type`, then we have the invariant:
- if the value `Term (ctx |- e : T)` is derived then for all subterms the associated judgement is valid using only the assumptions[1] on the subterm

[1] to be precise it's the recursive assumptions, ie if we have `x : A, y : P x |- y : P x` the term `y` only mentions the assumption `y`, then we look at the type of `y` in the context which mentions `x`, so both `x` and `y` are necessary.

**Comment by SkySkimmer** [comment]
Now we have the types in `Jdg` and `TT` which closely follow the type theory:
- a `TT.term` is easy to convert into a type theory term
- a `Jdg.Ctx.t` is easy to convert into a type theory context (using a topological ordering)
- a `Jdg.term` is easy to convert into a type theory judgement
- etc

So the invariants should be enough so that if we have a `Jdg.foo` then the corresponding type theory foo is derivable, plus stuff about the assumptions which should essentially say that `strengthen` and `shape` are valid.
This requires that the `Jdg.Env.t` used to create different values should be totally ordered by ancestry.

There is also an invariant that the context in a term/atom/type judgement is minimal with regards to the assumptions, but this property is not necessary for soundness.

**Comment by andrejbauer** [comment]
It should now be easy to state the invariants for `nucleus`.
