### ISSUE TITLE
How to implement records

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#40]
Currently the record types are implemented so that they may contain any number of fields:

    { lbl1 : type1 ; ... ; lblN : typeN }

This is convenient for the user, but it makes the code hairy. Also, it's going to make record types hard to work with on the meta-level in `tt`. Here is another possibility: we define a primitive dependent sum which has just two fields with fixed names `fst` and `snd`:

    { fst : type1 ; snd : type2 }

(of course `type2` depends on `type1`) We then provide sufficient sugar for the general records (as above) to be implemented as nested dependent sums. We would still have labels and all that, so to the user it would all look like it does now. But in addition any theorem stated about dependent sum would apply to any record type.

One drawback is that we would need to treat records with a single field differently.

I wonder how hard it would be to do this. Essentially we need to map teh labels `lblN` to suitable combinations of projections `snd.snd. ....snd.fst`.

**Comment by andrejbauer** [comment]
Here's another idea: http://research.microsoft.com/pubs/65409/scopedlabels.pdf

**Comment by jonsterling** [comment]
Thanks for the link, I'll give it a read! I need to resume thinking about records at some point soon, since we're really feeling the pain without them in [JonPRL](http://github.com/jonsterling/jonprl), and whilst I previously had intended to go the dependent intersection route I mentioned here last June, they are honestly just horrible to use in practice. Last time I spoke with Bob Constable, he still seemed very gung ho about them, but I suspect he has not actually used them except in theory.

**Comment by andrejbauer** [comment]
We're hoping to equate records and modules, more or less.

**Comment by andrejbauer** [comment]
A version of records has been implemented a while ago.
