### ISSUE TITLE
Print type of a term judgement

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#476]
When a term judgement is computed and printed out, it does not show the type of the term, e.g.:

```
# {x : A} x
- : judgement = ⊢ {x : A} x
```

This should probably be

```
# {x : A} x
- : judgement = ⊢ {x : A} x : A
```

**Comment by anjapetkovic** [comment]
- [ ] In runtime put printing environment to dynamic environment instead of lexical
- [ ] In nucleus implement function `abstracted_judgement_with_boundary: judgement_abstraction -> (judgement * boundary) abstraction`
- [ ] in nucleus implement printing of abstracted judgement with boundary 
- [ ] runtime prints judgements with boundaries, which should only affect printing of term judgements.
