### ISSUE TITLE
Get rid of constants

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#75]
Because they're annoying.

**Comment by andrejbauer** [comment]
This is a tricky question. I would prefer for @vladimirias to chime in. Here is the thing. We have introduced into Andromeda "constants" that have a fixed arity. A typical example:

    Axiom prod [_ _ : Type] : Type.

This says that `prod` is a constant which takes two types as an argument and returns a type. Most importantly, `prod` *must always be fully applied*. That is, if we had

    Axiom prod2 : Type -> Type -> Type.

then we could write `prod2 nat`, while `prod nat` is forbidden. If one really wants to write `prod nat` then it has to be done as something like this:

    Let prod3 := lambda [A B : Type] prod A B.

Then you can write `prod3 nat`.

There are reasons for having such constants. From a technical point of view we could probably live without them, but from a semantic point of view it may be important to keep them. It may be difficult to explain the meaning of `prod nat`, because it is something that lives outside type theory.

**Comment by vladimirias** [comment]
Shouldn’t Prod bound a variable in one of the arguments?

**Comment by andrejbauer** [comment]
Here `prod` is the cartesian product: it takes two types and gives a type. In terms of Coq its type is `Type -> Type -> Type`. It is not dependent. Perhaps you're thinking of the pairing, which in terms of Coq has the type

     pair : forall (A B : Type), A -> B -> prod A B

**Comment by andrejbauer** [comment]
I am going to close this. I think we do need constants of some sort because we cannot track everything to death in contexts. And in any case, there is a semantic difference between having `x : A ⊢ e[x] : B` and having ` ⊢ c : A` together with ` ⊢ e[c] : B`.
