### ISSUE TITLE
Recursion bug (?)

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#87]
See https://github.com/SkySkimmer/andromeda/blob/user-equal/tests/list-append.m31 for an example: 2 append functions are defined with a minor difference, then we fail a match to print the results.
The second function gives the expected result, but the first does not.

I'm not certain that this is a bug with recursion, that just seems like the most likely culprit.

**Comment by andrejbauer** [comment]
As it turns out it's a desugaring bug. We're going to solve it by simplifying the language os that there is no distinction between computations and expressions. This will make desugaring simpler. But we want to think carefully about such a move, see #88.

The temporary fix is to say that the arguments of a tag are computations, which I think is what @SkySkimmer will do.

**Comment by andrejbauer** [comment]
Closed by #89
